import QueryClientProviders from '@/components/providers/query-client-provider';
import RootLayoutShell from '@/layouts/root-layout';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: '--font-poppins',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="vi" suppressHydrationWarning>
			<body
				className={`${poppins.variable} antialiased`}
				suppressHydrationWarning
			>
				<QueryClientProviders>
					<RootLayoutShell>{children}</RootLayoutShell>
				</QueryClientProviders>
			</body>
		</html>
	);
}
